# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-28 03:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(blank=True, default=1, help_text='审批优先级', null=True, verbose_name='审批优先级')),
                ('show', models.BooleanField(default=False, help_text='优先级到当前用户，才展示该审批单')),
                ('approval_result', models.IntegerField(choices=[(0, '未处理'), (1, '审批通过'), (2, '退回申请')], default=2, help_text='审批结果', verbose_name='审批结果')),
                ('approval_comment', models.CharField(help_text='审批意见', max_length=200, null=True, verbose_name='审批意见')),
                ('time_approved', models.DateTimeField(auto_now_add=True, help_text='审批时间', verbose_name='审批时间')),
                ('time_received', models.DateTimeField(auto_now_add=True, help_text='到达时间', verbose_name='到达时间')),
            ],
            options={
                'verbose_name': '用户审批表',
                'db_table': 'oa_approval_process',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_route_user', models.IntegerField(default=1, help_text='当前用户处理完后，根据优先级指定下一个人审批', null=True, verbose_name='根据优先级指定下一个审批人')),
                ('title', models.CharField(help_text='申请标题', max_length=64, verbose_name='申请标题')),
                ('status', models.IntegerField(default=0, help_text='流程状态', verbose_name='流程状态')),
                ('desc', models.CharField(help_text='备注描述', max_length=255, null=True, verbose_name='备注描述')),
                ('time_create', models.DateTimeField(auto_now_add=True, help_text='流程创建时间', verbose_name='流程创建时间')),
                ('time_finished', models.DateTimeField(auto_now_add=True, help_text='流程完结时间', verbose_name='流程完结时间')),
            ],
            options={
                'verbose_name': '流程表',
                'db_table': 'oa_process',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='approvalprocess',
            name='process',
            field=models.ForeignKey(help_text='所属流程', on_delete=django.db.models.deletion.CASCADE, related_name='process', to='process.Process', verbose_name='所属流程'),
        ),
    ]
