# Generated by Django 2.2.1 on 2019-07-09 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='申请标题', max_length=64, verbose_name='申请标题')),
                ('cur_priority', models.IntegerField(blank=True, default=1, help_text='当前审批级别（默认：1）', null=True, verbose_name='当前审批级别')),
                ('status', models.IntegerField(choices=[(0, '审批中'), (1, '流程通过'), (2, '流程拒绝')], default=0, help_text='流程状态', verbose_name='流程状态')),
                ('desc', models.TextField(help_text='备注描述', max_length=255, null=True, verbose_name='备注描述')),
                ('time_create', models.DateTimeField(auto_now_add=True, help_text='流程创建时间', verbose_name='流程创建时间')),
                ('time_finished', models.DateTimeField(auto_now=True, help_text='流程完结时间', verbose_name='流程完结时间')),
                ('approver', models.ForeignKey(help_text='流程申请人', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='流程申请人')),
            ],
            options={
                'verbose_name': '流程表',
                'db_table': 'oa_process',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(blank=True, default=1, help_text='审批优先级', null=True, verbose_name='审批优先级')),
                ('show', models.BooleanField(default=False, help_text='优先级到当前用户，才展示该审批单', verbose_name='审批单展示')),
                ('approval_result', models.IntegerField(choices=[(0, '待处理'), (1, '审批通过'), (2, '退回申请')], default=0, help_text='审批结果', verbose_name='审批结果')),
                ('approval_comment', models.TextField(help_text='审批意见', max_length=200, null=True, verbose_name='审批意见')),
                ('time_approved', models.DateTimeField(auto_now_add=True, help_text='审批时间', verbose_name='审批时间')),
                ('time_received', models.DateTimeField(auto_now=True, help_text='到达时间', verbose_name='到达时间')),
                ('applicant', models.ForeignKey(help_text='审批人', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('process', models.ForeignKey(help_text='所属流程', on_delete=django.db.models.deletion.CASCADE, to='process.Process', verbose_name='所属流程')),
            ],
            options={
                'verbose_name': '用户审批表',
                'db_table': 'oa_approval_process',
                'ordering': ['id'],
            },
        ),
    ]
