# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-29 06:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('process', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalprocess',
            name='applicant',
            field=models.ForeignKey(help_text='审批人', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='审批人'),
        ),
        migrations.AddField(
            model_name='process',
            name='approver',
            field=models.ForeignKey(help_text='流程申请人', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='流程申请人'),
        ),
        migrations.AlterField(
            model_name='approvalprocess',
            name='process',
            field=models.ForeignKey(help_text='所属流程', on_delete=django.db.models.deletion.CASCADE, to='process.Process', verbose_name='所属流程'),
        ),
    ]
