# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-29 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0002_auto_20181029_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalprocess',
            name='time_received',
            field=models.DateTimeField(auto_now=True, help_text='到达时间', verbose_name='到达时间'),
        ),
        migrations.AlterField(
            model_name='process',
            name='next_route_user',
            field=models.IntegerField(default=1, help_text='当前用户处理完后，根据优先级指定下一个人审批', null=True, verbose_name='指定下一个审批人'),
        ),
        migrations.AlterField(
            model_name='process',
            name='time_finished',
            field=models.DateTimeField(auto_now=True, help_text='流程完结时间', verbose_name='流程完结时间'),
        ),
    ]
