# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-29 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0003_auto_20181029_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='next_route_user',
        ),
        migrations.AddField(
            model_name='process',
            name='next_user',
            field=models.IntegerField(default=1, help_text='当前用户处理完后，根据优先级指定下一个人审批', null=True, verbose_name='下一个审批人'),
        ),
        migrations.AlterField(
            model_name='approvalprocess',
            name='approval_result',
            field=models.IntegerField(choices=[(0, '待处理'), (1, '审批通过'), (2, '退回申请')], default=2, help_text='审批结果', verbose_name='审批结果'),
        ),
        migrations.AlterField(
            model_name='approvalprocess',
            name='show',
            field=models.BooleanField(default=False, help_text='优先级到当前用户，才展示该审批单', verbose_name='审批单展示'),
        ),
    ]
