# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-29 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0004_auto_20181029_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalprocess',
            name='approval_comment',
            field=models.TextField(help_text='审批意见', max_length=200, null=True, verbose_name='审批意见'),
        ),
        migrations.AlterField(
            model_name='process',
            name='desc',
            field=models.TextField(help_text='备注描述', max_length=255, null=True, verbose_name='备注描述'),
        ),
        migrations.AlterField(
            model_name='process',
            name='next_user',
            field=models.IntegerField(blank=True, default=1, help_text='当前用户处理完后, 根据优先级指定下一个人审批, 存储UserID', null=True, verbose_name='下一个审批人'),
        ),
        migrations.AlterField(
            model_name='process',
            name='status',
            field=models.IntegerField(choices=[(0, '审批中'), (1, '流程通过'), (2, '流程拒绝')], default=0, help_text='流程状态', verbose_name='流程状态'),
        ),
    ]
