# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-01 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0005_auto_20181029_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='next_user',
        ),
        migrations.AddField(
            model_name='process',
            name='next_priority',
            field=models.IntegerField(blank=True, default=1, help_text='当前审批级别的任意审批人通过后，根据优先级指定下一个审批级别', null=True, verbose_name='下一个审批级别'),
        ),
        migrations.AlterField(
            model_name='approvalprocess',
            name='approval_result',
            field=models.IntegerField(choices=[(0, '待处理'), (1, '审批通过'), (2, '退回申请')], default=0, help_text='审批结果', verbose_name='审批结果'),
        ),
    ]
