# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-30 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0006_auto_20181101_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='next_priority',
        ),
        migrations.AddField(
            model_name='process',
            name='cur_priority',
            field=models.IntegerField(blank=True, default=1, help_text='当前审批级别（默认：1）', null=True, verbose_name='当前审批级别'),
        ),
    ]
