# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-27 14:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ForeignKey(help_text='部门', null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Department', verbose_name='部门'),
        ),
    ]
