# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-28 02:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20180927_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='parent_dept',
            field=models.ForeignKey(help_text='子部门门', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='account.Department', verbose_name='子部门'),
        ),
    ]
