# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-29 06:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20181028_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='applicant',
        ),
        migrations.RemoveField(
            model_name='user',
            name='approver',
        ),
    ]
